from __future__ import annotations

from openpyxl import Workbook

from pole_route.importers.pea_gis import (
    PEAGISImportError,
    default_pole_inclusion,
    discover_pea_workbook,
    import_ds_poles,
    parse_height_metres,
    parse_voltage_kv,
)

HEADERS = ["Pole ID", "Latitude", "Longitude", "Height", "Voltage", "Owner"]


def _save_workbook(path, *, include_ds_pole=True, active_other=True):
    workbook = Workbook()
    cover = workbook.active
    cover.title = "Cover"
    cover.append(["PEA GIS export"])
    if include_ds_pole:
        poles = workbook.create_sheet("DS_Pole")
        poles.append(HEADERS)
        poles.append(["P-001", 13.75, 100.50, "12 เมตร", "22 kV", "PEA"])
    workbook.create_sheet("DS_Transformer")
    if not active_other and include_ds_pole:
        workbook.active = workbook.sheetnames.index("DS_Pole")
    workbook.save(path)


def test_discovery_lists_all_sheets_and_finds_inactive_ds_pole(tmp_path) -> None:
    path = tmp_path / "pea.xlsx"
    _save_workbook(path)

    discovery = discover_pea_workbook(path)

    assert discovery.sheet_names == ("Cover", "DS_Pole", "DS_Transformer")
    assert tuple(sheet.name for sheet in discovery.supported_sheets) == (
        "DS_Pole", "DS_Transformer",
    )
    assert discovery.unsupported_ds_sheets == ()
    assert import_ds_poles(path)[0].source_sheet == "DS_Pole"


def test_discovery_classifies_conductor_and_meter_sheets_as_intentionally_excluded(
    tmp_path,
) -> None:
    path = tmp_path / "excluded.xlsx"
    workbook = Workbook()
    workbook.active.title = "DS_MVConductor"
    workbook.create_sheet("DS_LVConductor")
    workbook.create_sheet("DS_LowVoltageMeter")
    workbook.create_sheet("DS_Unknown")
    workbook.save(path)

    discovery = discover_pea_workbook(path)

    assert discovery.intentionally_excluded_ds_sheets == (
        "DS_MVConductor",
        "DS_LVConductor",
        "DS_LowVoltageMeter",
    )
    assert discovery.unsupported_ds_sheets == ("DS_Unknown",)


def test_missing_ds_pole_reports_visible_sheets(tmp_path) -> None:
    path = tmp_path / "missing.xlsx"
    _save_workbook(path, include_ds_pole=False)

    try:
        import_ds_poles(path)
    except PEAGISImportError as error:
        assert "DS_Pole worksheet was not found" in str(error)
        assert "DS_Transformer" in str(error)
    else:
        raise AssertionError("missing DS_Pole must fail clearly")


def test_height_parser_accepts_numeric_and_text_values() -> None:
    assert parse_height_metres(12) == 12.0
    assert parse_height_metres("12.5 m") == 12.5
    assert parse_height_metres("๑๔ เมตร") == 14.0
    assert parse_height_metres("unknown") is None


def test_voltage_parser_supports_v_kv_ranges_and_slashes() -> None:
    assert parse_voltage_kv("22 kV") == (22.0, 22.0)
    assert parse_voltage_kv("400/230 V") == (0.23, 0.4)
    assert parse_voltage_kv("12 - 24 KV") == (12.0, 24.0)
    assert parse_voltage_kv("22 kV / 33000 V") == (22.0, 33.0)
    assert parse_voltage_kv("unknown") == (None, None)


def test_default_filter_is_height_or_voltage() -> None:
    assert default_pole_inclusion(12.0, 0.4)
    assert default_pole_inclusion(9.0, 22.0)
    assert not default_pole_inclusion(9.0, 0.4)
    assert not default_pole_inclusion(None, None)


def test_import_preserves_raw_source_rows_and_excluded_records(tmp_path) -> None:
    path = tmp_path / "records.xlsx"
    workbook = Workbook()
    workbook.active.title = "Cover"
    sheet = workbook.create_sheet("DS_Pole")
    sheet.append(["Report generated by PEA"])
    sheet.append(HEADERS)
    sheet.append(["P-12", 13.1, 100.1, "12 m", "400 V", "PEA-A"])
    sheet.append(["P-LOW", 13.2, 100.2, "9 m", "400/230 V", "PEA-B"])
    sheet.append(["P-WARN", 13.3, 100.3, "?", "unknown", "PEA-C"])
    workbook.save(path)

    records = import_ds_poles(path)

    assert [record.source_id for record in records] == ["P-12", "P-LOW", "P-WARN"]
    assert [record.source_row for record in records] == [3, 4, 5]
    assert records[0].raw_attributes["Owner"] == "PEA-A"
    assert records[0].included_by_default
    assert not records[1].included_by_default
    assert not records[2].included_by_default
    assert records[2].qc_warnings == (
        "Pole height could not be normalized",
        "Voltage could not be normalized",
    )
